[package]
name = "estimate_pi"
version = "0.1.0"
authors = ["kenOfYugen <kenzone@gmail.com>"]

[target.'cfg(not(target_os = "emscripten"))'.dependencies]
rayon = "*"

[dependencies.prng]
path = "../prng"
